qualityFiltering:
  ITS1:
    minQualityPhred: 20
    minLength: 90
    maxLength: 2000
  ITS2:
    minQualityPhred: 20
    minLength: 90
    maxLength: 2000
  FULL_ITS:
    minQualityPhred: 20
    minLength: 300
    maxLength: 6000
  LSU:
    minQualityPhred: 20
    minLength: 900
qc_quality_profile: false
qc_plot_sample_level: false
primers:
#  fwd: "CTTGGTCATTTAGAGGAAGTAA" # ITSF1 (5'->3')
#  rev_rc: "CCCGTCTTGAAACACGG" # LRU3 (reverse complement)
  fwd: "AACTTAAAGGAATTGACGGAAG" # NS5 (SSU)
  rev_rc: "GGTAAGCAGAACTGGCG" # LRU3 (reverse complement)
region:
  LSU:
    classifier: "dada2"
    rdp_trained_model_dir: "$baseDir/data/db/RDP-LSU/RDPClassifier_fungiLSU_trainsetNo11_trained/"
subsample:
  enabled: true
  scenarios:
    - count: 20
      seed: 77
    - count: 50
      seed: 6
    - count: 167
      seed: 42
    - count: 1000
      seed: 11
    - count: 2000
      seed: 789
    - count: 2500
      seed: 23
  repetitions: 5
cluster:
  methods:
    - vsearch
    - nanoclust
  nanoclust:
    min_cluster_props: [0.1, 0.01, 0.005, 0.001, 0.0005, 0.0001, 0.00005]


taxonomic_assignment:
  enabled: false
  dnabarcoder:
    ref_db: 'data/db/unite2024/unite2024ITS.fasta'
    ref_classifications: 'data/db/unite2024/unite2024ITS.classification'
    cutoffs: 'data/db/dnabarcoder/unite2024ITS.unique.cutoffs.best.json'
extract:
  ITS1: false
  ITS2: false
  FULL_ITS: true
  LSU: false
exclude:
  - '20221208.Rep1_Run2_ITS_Fungal_database.Aspergillus_niger.BC44'
  - '20221208.Rep1_Run2_ITS_Fungal_database.Cryptococcus_albidus.BC58'
  - '20221208.Rep1_Run2_ITS_Fungal_database.Galactomyces_geotrichum.BC64'
  - '20221208.Rep1_Run2_ITS_Fungal_database.Meyerozyma_guillermondii.BC69'
  - '20221208.Rep1_Run2_ITS_Fungal_database.Yarrowia_lipolytica.BC82'
  - '20221208.Rep1_Run2_ITS_Fungal_database.Fusarium_proliferatum.BC63'
  - '20221208.Rep1_Run2_ITS_Fungal_database.Puccinia_triticina.BC26'
