qualityFiltering:
  ITS1:
    minQualityPhred: 20
    minLength: 90
    maxLength: 2000
  ITS2:
    minQualityPhred: 20
    minLength: 90
    maxLength: 2000
  FULL_ITS:
    minQualityPhred: 20
    minLength: 300
    maxLength: 6000
  LSU:
    minQualityPhred: 20
    minLength: 900
primers:
#  fwd: "CTTGGTCATTTAGAGGAAGTAA" # ITSF1 (5'->3')
#  rev_rc: "CCCGTCTTGAAACACGG" # LRU3 (reverse complement)
  fwd: "AACTTAAAGGAATTGACGGAAG" # NS5 (SSU)
  rev_rc: "GGTAAGCAGAACTGGCG" # LRU3 (reverse complement)
region:
  LSU:
    classifier: "dada2"
    rdp_trained_model_dir: "$baseDir/data/db/RDP-LSU/RDPClassifier_fungiLSU_trainsetNo11_trained/"
